### ISSUE TITLE
MacOS: sh: arp: command not found

### ISSUE THREAD

**Issue by superuser205** [jclehner/nmrpflash#72] opened 2021-01-19 21:49 UTC
Hi;

Trying to follow the steps and I am running the macOS binary. When I attempt to install the OEM firmware I see:

```
Waiting for phyiscal connection.
Advertising NMRP server on en5 ... \
sh: arp: command not found
sh: arp: command not found
```

Any assistance would be greatly appreciated!

**Comment by jclehner** [comment] 2021-01-20 07:46
That's weird. Which version of macOS? What happens if you type the following commands:

```
which arp
arp
echo $PATH
```

**Comment by superuser205** [comment] 2021-01-20 15:39
macOS Mojave v10.14.6

```
which arp -> [empty line]
arp -> -bash: arp: command not found
uname -a -> Darwin JEC502127651ML 18.7.0 Darwin Kernel Version 18.7.0: Tue Nov 10 00:07:31 PST 2020; root:xnu-4903.278.51~1/RELEASE_X86_64 x86_64
```
```
$PATH -> /opt/webOS_TV_SDK/CLI/bin:/Users/<User>/.jenv/shims:/Users/<User>/.jenv/bin:/Users/<User>/.rvm/gems/ruby-2.6.3/bin:/Users/<User>/.rvm/gems/ruby-2.6.3@global/bin:/Users/<User>/.rvm/rubies/ruby-2.6.3/bin:/usr/local/bin:/usr/local/sbin:/Users/<User>/.nvm/versions/node/v12.16.3/bin:/usr/local/git/bin:/usr/local/MacGPG2/bin:/usr/local/git/bin:/usr/bin:/bin:/Users/<User>/.rvm/bin
```

**Comment by superuser205** [comment] 2021-01-20 17:12
I used a newer macbook pro where `arp` was installed. Your project/tutorial was successful in installing the Netgear OEM firmware onto a hopeless and totally unresponsive R6260. Buying you a coffee for your efforts and assistance!

**Comment by jclehner** [comment] 2021-01-21 14:32
Your `PATH` is messed up. Both `/usr/sbin` and `/sbin` are missing, which explains why `/usr/sbin/arp` can't be called using just `arp`.

Judging from the many non-standard directories, it looks like you're setting `PATH` manually somewhere. If you want to add entries, it's best to use something like

```sh
# appending a custom directory
export PATH="${PATH}:/my/custom/path"

# prepending a custom directory
export PATH="/my/custom/path:${PATH}"
```

This way you won't forget any directories!

**Comment by jclehner** [comment] 2021-01-28 10:44
Closing this, as the issue isn't related to `nmrpflash` itself.

**Closed by jclehner** 2021-01-28 10:44 UTC
